version: '3'

services:

  # Backend Service
  backend:
    build: ./CORE
    environment:
      DEBUG: "nodemc:*"
    volumes:
      - ./:/CORE
    ports:
      - 8081:80

  # Database Service
  arangodb:
    image: arangodb/arangodb
    ports:
      - 8529:8529
    environment:
      ARANGO_ROOT_PASSWORD: supersecretpassword

  # Scheduler Service
  scheduler:
    build: ./scheduler
    environment:
      DEBUG: "nodemc:*"
    volumes:
      - ./:/scheduler
      - /var/run/docker.sock:/var/run/docker.sock
